# Generated by Django 3.1.3 on 2020-11-18 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=20)),
                ('number_questions', models.IntegerField()),
                ('minimum_pass_count', models.IntegerField()),
                ('weightage_each_question', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_answers_correct', models.IntegerField()),
                ('score', models.IntegerField()),
                ('quiz_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.quiztopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=250)),
                ('choice_one', models.CharField(max_length=50)),
                ('choice_two', models.CharField(max_length=50)),
                ('choice_three', models.CharField(max_length=50)),
                ('choice_four', models.CharField(max_length=50)),
                ('correct_answer', models.CharField(max_length=50)),
                ('quiz_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.quiztopic')),
            ],
        ),
    ]
