# Generated by Django 3.1.3 on 2020-11-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquiz',
            name='is_pass',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
