# Generated by Django 3.1.3 on 2020-11-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_userquiz_is_pass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquiz',
            name='is_pass',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='userquiz',
            name='score',
            field=models.IntegerField(blank=True),
        ),
    ]
